pages:
  stage: deploy
  script:
    - sudo rm -r /var/www/personal-portfolio/
    - sudo mkdir /var/www/personal-portfolio
    - sudo cp -r dist/* /var/www/personal-portfolio/
  artifacts:
    paths:
    - /var/www/personal-portfolio/
  only:
  - master